# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'false'
          slurm_node: 'false'
          role: 'prom/graf'
      - targets: ["10.161.101.50:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'false'
          slurm_node: 'true'
          role: 'slurm-master'
      - targets: ["10.161.101.50:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'false'
          slurm_node: 'true'
          role: 'slurm-compute'
      - targets: ["10.161.101.50:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'false'
          slurm_node: 'true'
          role: 'slurm-compute'
      - targets: ["10.161.101.50:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'true'
          slurm_node: 'false'
          role: 'lsf-master'
      - targets: ["10.161.101.50:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'true'
          slurm_node: 'false'
          role: 'lsf-compute'
      - targets: ["10.161.101.50:9100"]
        labels:
          app: "node_exporter"
          lsf_node: 'true'
          slurm_node: 'false'
          role: 'lsf-compute'

  - job_name: "slurm"
    static_configs:
      - targets: ["10.161.101.50:9817"]
        labels:
          app: "slurm_exporter"

  - job_name: "lsf"
    static_configs:
      - targets: ["10.161.101.50:9818"]
        labels:
          app: "lsf_exporter"
